remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: Dean Attali
author: Dean Attali


navbar-links:
  Blog: "/"
  Hire me: "https://attalitech.com/"
  Projects: "projects"
  About Me / Contact: "aboutme"
  ❤ Support: "https://github.com/sponsors/daattali"

avatar: "/assets/img/deanimg.jpeg"

social-network-links:
  email: "daattali@gmail.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/3943160/daattali"
  calendly: "attalitech/meeting"
  youtube: "channel/UCR3No6pYhA1S7FZ0PbLKlgQ"
  patreon: DeanAttali

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "rstats,r,r shiny,shiny apps,r shiny apps,shiny developer,r shiny developer,shiny consultant,dashboards r,interactive dashboards"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

timezone: "America/Toronto"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

disqus: "deanattali-site"
google_analytics: "UA-59820529-1"
fb_app_id: "536330676521989"

url-pretty: "❤ Support"
url-canonical: https://github.com/sponsors/daattali

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, purpleads.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, purpleads.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      before-content: [support_promo_box.html, carbonads.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

# 2fc73a3a967e97599c9763d05e564189d5
