# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://deanattali.com"
baseurl: ""

# Brief name and description of the site
title: Dean Attali
description: "R-Shiny developer and consultant with a MSc in Bioinformatics and a Bachelor of Computer Science. Previously a software engineer at Google, IBM, and Wish.com."

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/deanimg.jpeg"

# List of links in the navigation bar
navbar-links:
  Blog: ""
  Shiny: "https://attalitech.com/"
  Projects: "projects"
  About Me / Contact: "aboutme"
  ‚ù§ Support: "https://github.com/sponsors/daattali"


# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Dean Attali
  email: "dean@attalitech.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/3943160/daattali"
  calendly: "attalitech/meeting"
  
# Select which links to show in the footer  
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: true
  calendly: true
  telephone: false
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "deanattali.com" 

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "deanattali-site"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-59820529-1"  # Your Google Analytics ID

fb_app_id: "536330676521989"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Default YAML values (more information on Jekyll's site)  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts 		
      show-share: true # add sharing buttons to all blog posts		
      show-subscribe: true # add subscribe email to all blog posts
      carbonads: true
      support_promo_box: true
      social-share: true
      footer-extra: purpleads.html
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# 2fc73a3a967e97599c9763d05e564189
